name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          openjdk-8-jdk \
          git \
          zip \
          unzip \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo6 \
          cmake \
          libffi-dev \
          libssl-dev

    - name: Install Buildozer and dependencies
      run: |
        pip3 install buildozer
        pip3 install cython==0.29.33
        pip3 install virtualenv

    - name: Build with Buildozer (with logging)
      run: |
        # تنظيف أولي
        buildozer android clean 2>/dev/null || true
        
        # البناء مع تسجيل مفصل
        buildozer -v android debug 2>&1 | tee build.log
        
        # إذا فشل، اعرض التفاصيل
        if [ ${PIPESTATUS[0]} -ne 0 ]; then
            echo "=== BUILD FAILED - LAST 50 LINES ==="
            tail -50 build.log
            echo "=== FULL BUILD LOG ==="
            cat build.log
            exit 1
        fi

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: myapp-apk
        path: bin/*.apk

    - name: Upload build log (if failed)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-log
        path: build.log
