name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          openjdk-8-jdk \
          git \
          zip \
          unzip \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo6 \
          cmake \
          libffi-dev \
          libssl-dev

    - name: Install Buildozer and dependencies
      run: |
        pip3 install buildozer==1.2.0
        pip3 install cython==0.29.33
        pip3 install virtualenv

    - name: Verify project structure
      run: |
        echo "=== Project Contents ==="
        ls -la
        echo "=== Python Files ==="
        find . -name "*.py" | head -10
        echo "=== Buildozer Spec Check ==="
        if [ -f buildozer.spec ]; then
            echo "buildozer.spec exists"
            cat buildozer.spec | head -20
        else
            echo "ERROR: buildozer.spec not found!"
        fi

    - name: Build with Buildozer (debug mode)
      run: |
        # تنظيف أي بناء سابق
        buildozer android clean 2>/dev/null || true
        
        # البناء مع تسجيل مفصل
        echo "Starting Buildozer build..."
        buildozer -v android debug 2>&1 | tee build.log
        BUILD_STATUS=${PIPESTATUS[0]}
        
        if [ $BUILD_STATUS -ne 0 ]; then
            echo "=== BUILD FAILED - FIRST 50 LINES ==="
            head -50 build.log
            echo "=== BUILD FAILED - LAST 20 LINES ==="
            tail -20 build.log
            exit 1
        fi

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: myapp-apk
        path: bin/*.apk

    - name: Upload build log
      uses: actions/upload-artifact@v4
      with:
        name: build-log
        path: build.log
